module.exports= function(app)
{
    app.get('/Doctree_index',(req,res)=>
    {
        res.render('Doctree_index');
    });
    app.post('/Doctree_index',(req,res)=>
    {
        res.render('Doctree_index');
    });
    app.get('/Doctree_about-us',(req,res)=>
    {
        res.render('Doctree_about-us');
    });
    app.get('/price',(req,res)=>
    {
        res.render('price');
    });
    app.get('/Doctree_contact',(req,res)=>
    {
        res.render('Doctree_contact')
    });
    app.get('/Registration/registration',(req,res)=>
    {
        res.render('Registration/registration')
    });
    app.post('/reg_form/login',function(req,res)
    {
        res.render('reg_form/login');
    });

};